services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - "27017:27017"
    volumes:
        - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
        - MONGO_INITDB_DATABASE=FoodOrder_Cardapio
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "80"
      - "443"
    environment:
      - MONGODB_CONNECTION=mongodb://mongodb:27017/FoodOrder_Cardapio
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      mongodb:
        condition: service_healthy
        