services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - "27017:27017"
    volumes:
        - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
        - MONGO_INITDB_DATABASE=FoodOrder_Cardapio
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    # usar FORA do debug
    image: japamanoel/foodorder_cardapio:latest
    container_name: foodorder_cardapio
    #inicio---//---- usar no modo debug
    # image: ${DOCKER_REGISTRY-}api
    # build:
    #   context: .
    #   dockerfile: Api/Dockerfile
    #fim---//---- usar no modo debug
    ports:
      - "8080:80"
    environment:
      - MONGODB_CONNECTION=mongodb://mongodb:27017/FoodOrder_Cardapio
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      mongodb:
        condition: service_healthy
        
  tests:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: foodorder_cardapio_tests
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MONGODB_CONNECTION=mongodb://mongodb:27017/FoodOrder_Cardapio
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: ["dotnet", "test", "Tests/Tests.csproj"]