name: Test and Report Coverage

on:
  push:
    branches:
      - fase_4
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore FoodOrder_Cardapio.sln

      - name: Build
        run: dotnet build FoodOrder_Cardapio.sln --no-restore

      - name: Run tests and collect coverage
        run: |
          dotnet test FoodOrder_Cardapio.sln \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./Tests/Coverage/XML

      - name: Generate HTML Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:"./Tests/Coverage/XML/**/*.xml" \
            -targetdir:"./Tests/Coverage/Report" \
            -reporttypes:Html

      - name: Convert coverage to Coveralls format
        run: |
          dotnet tool install --global coveralls.net
          coveralls.net --opencover -i ./Tests/Coverage/XML/coverage.cobertura.xml -r ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload coverage report
        run: echo "Coverage uploaded to Coveralls"
