name: Test and Report Coverage

on:
  push:
    branches:
      - fase_4
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install .NET 6.0 (for Coveralls)
        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/5d04d580-beb0-48cc-bda7-e8b02133b038/76a4a83b83130e3b6b72d48b3d1ac8fc/dotnet-sdk-6.0.414-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.0.414-linux-x64.tar.gz -C $HOME/dotnet
          export PATH=$PATH:$HOME/dotnet
          dotnet --version

      - name: Install dependencies
        run: dotnet restore FoodOrder_Cardapio.sln

      - name: Build
        run: dotnet build FoodOrder_Cardapio.sln --no-restore

      - name: Run tests and collect coverage
        run: |
          dotnet test FoodOrder_Cardapio.sln \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./Tests/Coverage/XML

      # Verificar se os arquivos de cobertura estão sendo gerados corretamente
      - name: List coverage files
        run: |
          ls -la ./Tests/Coverage/

      - name: Generate HTML Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:"./Tests/Coverage/XML/**/*.xml" \
            -targetdir:"./Tests/Coverage/Report" \
            -reporttypes:Html

      - name: Install and run Coveralls
        run: |
          dotnet tool install --global coveralls.net
          # Adicionar o caminho da ferramenta global ao PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          # Rodar o Coveralls com o caminho correto para os arquivos XML
          csmacnz.Coveralls --opencover -i ./Tests/Coverage/XML/**/*.xml --repoToken ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload coverage report
        run: echo "Coverage uploaded to Coveralls"
